### ISSUE TITLE
Serializable issue on server

### ISSUE THREAD

**Issue by macfol** [macfol/Kamienica#155]
> WARNING: Cannot serialize session attribute SPRING_SECURITY_CONTEXT for session 47D5D78CC415D415E0AE7DE039D9039C
> java.io.NotSerializableException: kamienica.model.entity.RentContract
> 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
> 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
> 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
> 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
> 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
> 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
> 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
> 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
> 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
> 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
> 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
> 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
> 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
> 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
> 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
> 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
> 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
> 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
> 	at org.apache.catalina.session.StandardSession.doWriteObject(StandardSession.java:1702)
> 	at org.apache.catalina.session.StandardSession.writeObjectData(StandardSession.java:1094)
> 	at org.apache.catalina.session.StandardManager.doUnload(StandardManager.java:315)
> 	at org.apache.catalina.session.StandardManager.unload(StandardManager.java:265)
> 	at org.apache.catalina.session.StandardManager.stopInternal(StandardManager.java:384)
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
> 	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5415)
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
> 	at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3783)
> 	at org.apache.catalina.loader.WebappLoader.backgroundProcess(WebappLoader.java:293)
> 	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5553)
> 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1408)
> 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1412)
> 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1412)
> 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1380)
> 	at java.lang.Thread.run(Thread.java:748)
>

**Comment by macfol** [comment]
Not reproducible
