### ISSUE TITLE
Change field types

### ISSUE THREAD

**Issue by macfol** [macfol/Kamienica#56]
**POJOs ID should be changed from int to Long**
bigger range + able to be null
**Change util.date to joda.localTime**
more flexible
**Imlements Sieriazable (?)**

**Comment by macfol** [comment]
> WARNING: Cannot serialize session attribute SPRING_SECURITY_CONTEXT for session AA78ED89C81B100F7D07270C82CC6BAE
> java.io.NotSerializableException: kamienica.feature.apartment.Apartment
> 	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
> 	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
> 	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
> 	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
> 	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
> 	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
> 	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
> 	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
> 	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
> 	at java.io.ObjectOutputStream.defaultWriteFields(Unknown Source)
> 	at java.io.ObjectOutputStream.writeSerialData(Unknown Source)
> 	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
> 	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
> 	at java.io.ObjectOutputStream.writeObject(Unknown Source)
> 	at org.apache.catalina.session.StandardSession.doWriteObject(StandardSession.java:1709)
> 	at org.apache.catalina.session.StandardSession.writeObjectData(StandardSession.java:1107)
> 	at org.apache.catalina.session.StandardManager.doUnload(StandardManager.java:315)
> 	at org.apache.catalina.session.StandardManager.unload(StandardManager.java:265)
> 	at org.apache.catalina.session.StandardManager.stopInternal(StandardManager.java:384)
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:224)
> 	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5491)
> 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:224)
> 	at org.apache.catalina.core.StandardContext.reload(StandardContext.java:3822)
> 	at org.apache.catalina.loader.WebappLoader.backgroundProcess(WebappLoader.java:291)
> 	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5629)
> 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1376)
> 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1380)
> 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1380)
> 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1348)
> 	at java.lang.Thread.run(Unknown Source)
>
